feat:
terraform-ibm-modules/terraform-ibm-powervs-infrastructure pull request #352
Opened 2023-03-03 13:32 UTC by surajsbharadwaj

### Description

1. Downgrade terraform ibm provider version to 1.49.0 to make it compatible with secure landing zone vpc module.
2. Reorganized the example folder structure
3. Upgraded the examples to have a full stack solution (secure landing zone vpc plus Powervs infra deployed in one go).
4. Renamed the flavour for IBM catalog

### Types of changes in this PR

#### No release required

- [ ] Examples or tests (addition or updates of examples or tests)
- [ ] Documentation update
- [ ] CI-related update (pipeline, etc.)
- [ ] Other changes that don't affect Terraform code

#### Release required

- [ ] Bug fix (patch release (`x.x.X`): Change that fixes an issue and is compatible with earlier versions)
- [ ] New feature (minor release (`x.X.x`): Change that adds functionality and is compatible with earlier versions)
- [x] Breaking change (major release (`X.x.x`): Change that is likely incompatible with previous versions)

##### Release notes content

1. Downgrade terraform ibm provider version to 1.49.0 to make it compatible with secure landing zone vpc module.
2. Reorganized the example folder structure
3. Upgraded the examples to have a full stack solution (secure landing zone vpc plus Powervs infra deployed in one go).
4. Renamed the flavour for IBM catalog

---

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### Merge actions for mergers

- Merge by using "Squash and merge".
- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author.

    The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).

2023-03-03 13:41 UTC, surajsbharadwaj commented
@kbiegert could you please review the ibm_catalog.json file and the descriptions in it ?
@Beilmann  and @SirSpidey  **Docs:**
could you guys review :
- readme files especially the descriptions 
- Description in the variables file (under examples folder (examples/ibm-catalog/deployable-architectures/full-stack/variables.tf)

2023-03-03 14:38 UTC, SirSpidey requested changes
couple of small suggestions

2023-03-03 14:38 UTC, SirSpidey commented on examples/ibm-catalog/deployable-architectures/full-stack/README.md
> +    - Installs and configures the Squid Proxy, DNS Forwarder, NTP Forwarder and NFS on hosts, and sets the host as server for these services NTP, NFS, DNS using ansible roles.
```suggestion
This example sets up the following infrastructure:
- A VPC Infrastructure with the following components:
    -  Provisions three VPCs with one VSI in each VPC (one management(jump/bastion) VSI, one inet-svs VSI configured as squid proxy server, one private-svs VSI configured as NFS, NTP, DNS server).
    - Installs and configures the Squid Proxy, DNS Forwarder, NTP forwarder and NFS on hosts, and sets the host as the server for the NTP, NFS, and DNS services by using Ansible roles.
```

Made the list items parallel by starting with a verb, although I'm not wed to those verbs.

2023-03-03 14:38 UTC, SirSpidey commented on examples/ibm-catalog/deployable-architectures/full-stack/README.md
> +    - Creates a SSH key.
```suggestion
    - Creates an SSH key.
```

2023-03-03 14:38 UTC, SirSpidey commented on examples/ibm-catalog/deployable-architectures/full-stack/README.md
> +## Reference architectures
I think if you want to link to the diagram only, we should rename the section to **Architecture diagram**. To leave the heading, link to the `.md` file.

2023-03-03 17:55 UTC, kbiegert commented
I was thinking that the plan was going to be to retain the power infrastructure as a add on (keep it as is) and implement a new terraform that would represent the full stack by invoking the power infra and SLZ.  Is there a new plan?

2023-03-03 23:14 UTC, surajsbharadwaj commented
@kbiegert . In this release let's do it for full stack. On next pull request i will add the modified and more sensible code for extension.

2023-03-04 21:03 UTC, Beilmann commented
@surajsbharadwaj - you changed SLZ extension to full stack. We plan to have 2 variants: SLZ extension + full stack. Why not to keep also the existing one?

2023-03-04 21:52 UTC, surajsbharadwaj commented
@Beilmann let's discuss on Monday. We need 2 architecture diagrams. Variable description altered and may be more in detail about prerequisites. For this release it is full stack solution only. I think will have to recolor the architecture diagram to represent the full stack solution

2023-03-06 07:40 UTC, Beilmann commented
@surajsbharadwaj - names sind ok, from my point of view. Will rename and extend reference architectures in the same way.

2023-03-06 11:26 UTC, surajsbharadwaj commented
invalid. A new one will be created

2023-03-06 11:26 UTC, closed without merging