Import Workspace
terraform-ibm-modules/terraform-ibm-powervs-infrastructure pull request #694
Opened 2023-11-23 12:04 UTC by stafaniasaju

### Description

This PR includes the implementation for the new powervs infra flavour 'import-workspace'.

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2023-11-23 12:05 UTC, stafaniasaju commented
/run pipeline

2023-11-23 15:35 UTC, stafaniasaju commented on solutions/import-workspace/import_vpc.tf
> +# Creating acl rules for workload vpc
I believe this is N/A since it is not a segmentation comment.

2023-11-23 15:35 UTC, stafaniasaju commented on solutions/import-workspace/import_vpc.tf
> +# Creating security group rules for management, edge and workload vpcs
I believe this is N/A since it is not a segmentation comment.

2023-11-23 17:12 UTC, stafaniasaju commented on solutions/import-workspace/outputs.tf
> +  sensitive = true
Making it not sensitive

2023-11-23 23:09 UTC, surajsbharadwaj requested changes
Please see the comments. Total of 18 Comments

2023-11-23 23:09 UTC, surajsbharadwaj commented on solutions/import-workspace/import_vpc.tf
> +# Creating acl rules for management vpc
Create acl rules for management VPC

2023-11-23 23:09 UTC, surajsbharadwaj commented on solutions/import-workspace/import_vpc.tf
> +# Creating acl rules for edge vpc
Create acl rules for edge VPC

2023-11-23 23:09 UTC, surajsbharadwaj commented on solutions/import-workspace/import_vpc.tf
> +# Creating acl rules for workload vpc
Create acl rules for workload VPC

2023-11-23 23:09 UTC, surajsbharadwaj commented on solutions/import-workspace/import_vpc.tf
> +# Security Group Rule creation for management, edge and workload vpcs
Create Security Group Rules for management, edge and workload VPCs

2023-11-23 23:09 UTC, surajsbharadwaj commented on solutions/import-workspace/locals_vpc.tf
> +locals {
Add block comments:
####################################################
 Locals for outputs
####################################################

2023-11-23 23:09 UTC, surajsbharadwaj commented on solutions/import-workspace/locals_vpc.tf
> +
Add block comments
####################################################
Locals for creating ACL rules
####################################################

2023-11-23 23:09 UTC, surajsbharadwaj commented on solutions/import-workspace/locals_vpc.tf
> +locals {
Add block comments
####################################################
Locals for creating Security Group rules
####################################################

2023-11-23 23:09 UTC, surajsbharadwaj commented on solutions/import-workspace/outputs.tf
> +  description = "Zone where PowerVS infrastructure is created."
Zone of existing PowerVS infrastructure

2023-11-23 23:09 UTC, surajsbharadwaj commented on solutions/import-workspace/outputs.tf
> +  description = "SSH public key name and value in created PowerVS infrastructure."
created -->existing

2023-11-23 23:09 UTC, surajsbharadwaj commented on solutions/import-workspace/outputs.tf
> +  description = "Number of cloud connections configured in created PowerVS infrastructure."
existing

2023-11-23 23:09 UTC, surajsbharadwaj commented on solutions/import-workspace/variables.tf
> +  description = "IBM Cloud data center location where IBM PowerVS workspace is created."
IBM Cloud data center location where IBM PowerVS workspace exists

2023-11-27 22:03 UTC, surajsbharadwaj approved these changes

2023-11-27 22:04 UTC, merged